### PR TITLE
Add return of updated cursor in SwapProps

### PR DESCRIPTION
**Pull request by scarfacedeb**
Sometimes I want to get the resulted cursor after `this.swapProps`

### CODE REVIEW

**Comment by mikaelbr** [comment]
Very true! Some of the mixins and concept in `omniscient-mixins` need some more love and testing as well. But these functions should still be pure and transparent.

Thanks for the PR!

**Comment by scarfacedeb** [comment]
🎉 that was the swiftest response on PR that I've ever seen

**Comment by mikaelbr** [comment]
:cake:

**Comment by torgeir** [comment]
:beers:

**Pull request merged**
